### ISSUE TITLE
Whats the incentive for all caps folder names?

### ISSUE THREAD

**Issue by sebastiangraz** [gillesbertaux/bootsy#1]
I'm intrigued by this starter template, I think it's great! I'm just genuinely curious as to why all the folder names are in CAPS – what is the reasoning behind it? Thank you

**Comment by gillesbertaux** [comment]
Thank you, very glad you liked it! 

Yes every folder is in CAPS, actually there's no particular reason, it's just that at I used to name my folders this way. 

Also, I kept it it that way because I thought it gave more "weight" to every section. But if you think that's a problem, or that it impacts legibility, you can fork it :)
